name: bedug
description: Jadwal Sholat & Kalender Hijriyah â€” Pengingat Sholat Khas Nusantara
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  adhan: ^2.0.0+1
  hijri: ^3.0.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  home_widget: ^0.9.0
  flutter_local_notifications: ^20.1.0
  flutter_riverpod: ^3.2.1
  timezone: ^0.10.1
  shared_preferences: ^2.2.3
  intl: ^0.20.2
  cupertino_native: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

# App identifiers:
#   Android: com.bedug.app
#   iOS/macOS: com.bedug.app
#   Windows: com.bedug.app
